#!/bin/bash

(if [ -f /usr/lib/YaST2/bin/y2base ] ; then
	/usr/lib/YaST2/bin/y2base stdio scr -l - > /dev/null <<END_HERE
Read (.printerdb.lpd.vendors, "")
Read (.printerdb.deep_check)
END_HERE
else
	/usr/lib/YaST2/bin/y2bignfat stdio scr -l - > /dev/null <<END_HERE
Read (.printerdb.lpd.vendors, "")
Read (.printerdb.deep_check)
END_HERE
fi) 2>&1 | grep ag_printerdb

