#!/bin/bash

if [ -f /tmp/printerdb.tst ] ; then
	rm -f /tmp/printerdb.tst || (echo "Can not remove /tmp/printerdb.tst" && exit 1)
fi

if [ -f /tmp/printerdb.wrong ] ; then
	rm -f /tmp/printerdb.wrong || (echo "Can not remove /tmp/printerdb.wrong" && exit 1)
fi

if [ -f /tmp/printerdb.sh ] ; then
	rm -f /tmp/printerdb.sh || (echo "Can not remove /tmp/printerdb.sh" && exit 1)
fi

(if [ -f /usr/lib/YaST2/bin/y2base ] ; then
	/usr/lib/YaST2/bin/y2base stdio scr -l - <<END_HERE
Write (.printerdb.testscript, "/tmp/printerdb.tst")
END_HERE
else
	/usr/lib/YaST2/bin/y2bignfat stdio scr -l - <<END_HERE
Write (.printerdb.testscript, "/tmp/printerdb.tst")
END_HERE
fi) 2>&1 | grep \<3\>


awk ' /^PARAM/ {
    $1 = ""
    print "gs -dNOPAUSE -sOutputFile=/dev/null " $0 " /usr/share/doc/packages/ghostscript/examples/colorcir.ps quit.ps || echo $CONFIG " $0 "| tee -a /tmp/printerdb.wrong\n"

}
/^export CONFIG=/ { print $0 " ; echo $CONFIG sleeping 5 seconds until start ; sleep 5" }
' /tmp/printerdb.tst > /tmp/printerdb.sh
chmod 0755 /tmp/printerdb.sh

echo -e 'now execute /tmp/printerdb.sh\nfor example do:\n /tmp/printerdb.sh 2>&1 | tee /tmp/printerdb.out'
