#!/bin/bash

function get_paper () {
    (
	. /etc/sysconfig/language &> /dev/null
	read h w r < <(LANG=$RC_LANG LC_ALL=$RC_LC_ALL LC_PAPER=$RC_LC_PAPER locale -k LC_PAPER)
	case "$h" in
	    height=297) echo "\$[\"value\":\"A4\"]"	    ;;
	    height=279) echo "\$[\"value\":\"Letter\"]" ;;
            *)          echo "\$[\"value\":\"\"]";;
	esac
    )
}

while true ; do
read COMMAND || exit
    # strip leading backquote introduced by NI
    COMMAND=${COMMAND#\`}

    case "$COMMAND" in
        "result ("*)
            exit
            ;;
        "Read ("*)
	    get_paper
	    ;;
        *)
            echo nil

    esac
 done
